/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'team-members': TeamMember;
    'trusted-logos': TrustedLogo;
    testimonials: Testimonial;
    'news-posts': NewsPost;
    'job-posts': JobPost;
    'contact-submissions': ContactSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    'trusted-logos': TrustedLogosSelect<false> | TrustedLogosSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'news-posts': NewsPostsSelect<false> | NewsPostsSelect<true>;
    'job-posts': JobPostsSelect<false> | JobPostsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'id' | 'zh') | ('en' | 'id' | 'zh')[];
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    'about-page': AboutPage;
    'services-page': ServicesPage;
    'platform-page': PlatformPage;
    'newsroom-page': NewsroomPage;
    'careers-page': CareersPage;
    'contact-page': ContactPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'services-page': ServicesPageSelect<false> | ServicesPageSelect<true>;
    'platform-page': PlatformPageSelect<false> | PlatformPageSelect<true>;
    'newsroom-page': NewsroomPageSelect<false> | NewsroomPageSelect<true>;
    'careers-page': CareersPageSelect<false> | CareersPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
  };
  locale: 'en' | 'id' | 'zh';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  role: string;
  /**
   * Use this after image assets are migrated into Payload.
   */
  image?: (number | null) | Media;
  /**
   * Current Framer/CDN image URL used by the static site.
   */
  externalImageUrl?: string | null;
  imageAlt: string;
  sortOrder: number;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trusted-logos".
 */
export interface TrustedLogo {
  id: number;
  name: string;
  sourceType: 'media' | 'externalUrl' | 'inlineSvg' | 'sourceSymbol';
  media?: (number | null) | Media;
  externalUrl?: string | null;
  svgMarkup?: string | null;
  /**
   * Matches the symbol ID currently embedded in the static about page.
   */
  sourceSymbolId?: string | null;
  /**
   * SVG viewBox for inline SVG or source symbol rendering.
   */
  viewBox?: string | null;
  /**
   * Optional customer URL when logo clicks are enabled.
   */
  destinationUrl?: string | null;
  sortOrder: number;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  company: string;
  image?: (number | null) | Media;
  externalImageUrl?: string | null;
  sortOrder: number;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-posts".
 */
export interface NewsPost {
  id: number;
  title: string;
  slug: string;
  category: 'news' | 'insights';
  excerpt: string;
  author: string;
  intro: string;
  coverImage?: (number | null) | Media;
  externalCoverImageUrl?: string | null;
  /**
   * Optional rich text for future-rendered article bodies.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  contentSections: {
    heading: string;
    body: string;
    id?: string | null;
  }[];
  publishedAt?: string | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-posts".
 */
export interface JobPost {
  id: number;
  title: string;
  slug: string;
  department: string;
  location: string;
  employmentType: 'full-time' | 'part-time' | 'contract';
  postedDate?: string | null;
  summary: string;
  sidebarText?: string | null;
  jobDescription: string;
  responsibilities: {
    body: string;
    id?: string | null;
  }[];
  basicIntro?: string | null;
  basicRequirements: {
    body: string;
    id?: string | null;
  }[];
  preferredIntro?: string | null;
  preferredRequirements: {
    body: string;
    id?: string | null;
  }[];
  /**
   * Optional long-form content for future fully-rendered job pages.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  sortOrder: number;
  isOpen?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  productType?: string | null;
  orderQuantity?: string | null;
  companyName?: string | null;
  emailOrPhone: string;
  customerName?: string | null;
  destinationMarket?: string | null;
  message?: string | null;
  sourceUrl?: string | null;
  status: 'new' | 'contacted' | 'quoted' | 'closed';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'trusted-logos';
        value: number | TrustedLogo;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'news-posts';
        value: number | NewsPost;
      } | null)
    | ({
        relationTo: 'job-posts';
        value: number | JobPost;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  image?: T;
  externalImageUrl?: T;
  imageAlt?: T;
  sortOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trusted-logos_select".
 */
export interface TrustedLogosSelect<T extends boolean = true> {
  name?: T;
  sourceType?: T;
  media?: T;
  externalUrl?: T;
  svgMarkup?: T;
  sourceSymbolId?: T;
  viewBox?: T;
  destinationUrl?: T;
  sortOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  company?: T;
  image?: T;
  externalImageUrl?: T;
  sortOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-posts_select".
 */
export interface NewsPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  excerpt?: T;
  author?: T;
  intro?: T;
  coverImage?: T;
  externalCoverImageUrl?: T;
  content?: T;
  contentSections?:
    | T
    | {
        heading?: T;
        body?: T;
        id?: T;
      };
  publishedAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-posts_select".
 */
export interface JobPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  department?: T;
  location?: T;
  employmentType?: T;
  postedDate?: T;
  summary?: T;
  sidebarText?: T;
  jobDescription?: T;
  responsibilities?:
    | T
    | {
        body?: T;
        id?: T;
      };
  basicIntro?: T;
  basicRequirements?:
    | T
    | {
        body?: T;
        id?: T;
      };
  preferredIntro?: T;
  preferredRequirements?:
    | T
    | {
        body?: T;
        id?: T;
      };
  description?: T;
  sortOrder?: T;
  isOpen?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  productType?: T;
  orderQuantity?: T;
  companyName?: T;
  emailOrPhone?: T;
  customerName?: T;
  destinationMarket?: T;
  message?: T;
  sourceUrl?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  brandName: string;
  logoLabel: string;
  logoDisplay: 'text' | 'image';
  logoAlt?: string | null;
  logoHref?: string | null;
  /**
   * White PNG/SVG logo for dark or transparent header backgrounds.
   */
  logoImage?: (number | null) | Media;
  /**
   * White logo file URL. Used when no media upload is selected.
   */
  externalLogoImageUrl?: string | null;
  /**
   * Black PNG/SVG logo for light headers, menu overlays, and footer.
   */
  darkLogoImage?: (number | null) | Media;
  /**
   * Black logo file URL. Used when no media upload is selected.
   */
  externalDarkLogoImageUrl?: string | null;
  requestQuoteLabel: string;
  requestQuoteUrl: string;
  mainNavigation: {
    label: string;
    url: string;
    id?: string | null;
  }[];
  menuContact?: {
    quickContactLabel?: string | null;
    email?: string | null;
    messageLabel?: string | null;
    quoteLabel?: string | null;
    quoteUrl?: string | null;
  };
  footerContact?: {
    label?: string | null;
    heading?: string | null;
    buttonLabel?: string | null;
    buttonUrl?: string | null;
  };
  address?: string | null;
  footerColumns?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        label: string;
        url: string;
        icon: 'linkedin' | 'instagram' | 'youtube' | 'whatsapp';
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  credit?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  metaTitle?: string | null;
  hero: {
    breadcrumb: string;
    title: string;
    description: string;
    buttonLabel: string;
    buttonUrl: string;
    videoUrl?: string | null;
    posterUrl?: string | null;
  };
  services: {
    label: string;
    heading: string;
    cards: {
      title: string;
      description: string;
      id?: string | null;
    }[];
    buttonLabel?: string | null;
    buttonUrl?: string | null;
  };
  values: {
    number: string;
    title: string;
    description: string;
    id?: string | null;
  }[];
  technologyCta: {
    label: string;
    /**
     * HTML is used here so inline image chips can preserve the Framer-style headline.
     */
    headingHtml: string;
    buttonLabel?: string | null;
    buttonUrl?: string | null;
  };
  howWeWork: {
    label: string;
    body: string;
    steps: {
      number: string;
      body: string;
      id?: string | null;
    }[];
  };
  newsroom: {
    label: string;
    heading: string;
    posts?: (number | NewsPost)[] | null;
  };
  finalCta?: {
    label?: string | null;
    heading?: string | null;
    buttonLabel?: string | null;
    buttonUrl?: string | null;
    backgroundImage?: (number | null) | Media;
    externalBackgroundImageUrl?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  metaTitle?: string | null;
  pageTitle: string;
  heroImage?: (number | null) | Media;
  externalHeroImageUrl: string;
  whoWeAre: {
    label: string;
    heading: string;
    columns: {
      body: string;
      id?: string | null;
    }[];
  };
  reach: {
    label: string;
    heading: string;
    locations: {
      country: string;
      city: string;
      id?: string | null;
    }[];
    globeVideoUrl?: string | null;
  };
  metrics: {
    label: string;
    heading: string;
    image?: (number | null) | Media;
    externalImageUrl?: string | null;
    imageAlt?: string | null;
    subtext?: string | null;
    items: {
      value: string;
      label: string;
      tone: 'dark' | 'gray' | 'yellow' | 'charcoal';
      id?: string | null;
    }[];
  };
  testimonials?: (number | Testimonial)[] | null;
  trustedLabel: string;
  trustedLogos?: (number | TrustedLogo)[] | null;
  teamLabel: string;
  teamHeading: string;
  teamMembers?: (number | TeamMember)[] | null;
  careersCta?: {
    label?: string | null;
    heading?: string | null;
    buttonLabel?: string | null;
    buttonUrl?: string | null;
  };
  finalCta?: {
    label?: string | null;
    heading?: string | null;
    buttonLabel?: string | null;
    buttonUrl?: string | null;
    backgroundImage?: (number | null) | Media;
    externalBackgroundImageUrl?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page".
 */
export interface ServicesPage {
  id: number;
  metaTitle?: string | null;
  hero: {
    label: string;
    title: string;
    description: string;
    backgroundImage?: (number | null) | Media;
    externalBackgroundImageUrl: string;
    imageAlt?: string | null;
  };
  focus: {
    label: string;
    heading: string;
    paragraphs: {
      body: string;
      id?: string | null;
    }[];
  };
  aerial: {
    image?: (number | null) | Media;
    externalImageUrl: string;
    imageAlt?: string | null;
    labels: {
      label: string;
      id?: string | null;
    }[];
  };
  services: {
    heading: string;
    items: {
      number: string;
      title: string;
      description: string;
      image?: (number | null) | Media;
      externalImageUrl: string;
      imageAlt: string;
      id?: string | null;
    }[];
  };
  industries: {
    title: string;
    image?: (number | null) | Media;
    externalImageUrl: string;
    imageAlt?: string | null;
    items: {
      name: string;
      id?: string | null;
    }[];
  };
  finalCta?: {
    label?: string | null;
    heading?: string | null;
    buttonLabel?: string | null;
    buttonUrl?: string | null;
    backgroundImage?: (number | null) | Media;
    externalBackgroundImageUrl?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-page".
 */
export interface PlatformPage {
  id: number;
  metaTitle?: string | null;
  hero: {
    label: string;
    title: string;
    description: string;
    backgroundImage?: (number | null) | Media;
    externalBackgroundImageUrl: string;
  };
  interfaceIntro: {
    label: string;
    body: string;
  };
  tabletMockup: {
    image?: (number | null) | Media;
    externalImageUrl: string;
    imageAlt?: string | null;
  };
  featureSections: {
    label: string;
    heading: string;
    body: string;
    image?: (number | null) | Media;
    externalImageUrl: string;
    imageAlt: string;
    id?: string | null;
  }[];
  whyChoose: {
    label: string;
    body: string;
    backgroundImage?: (number | null) | Media;
    externalBackgroundImageUrl: string;
  };
  highlights: {
    label: string;
    heading: string;
    items: {
      number: string;
      body: string;
      icon?: (number | null) | Media;
      externalIconUrl: string;
      iconAlt?: string | null;
      id?: string | null;
    }[];
  };
  finalCta?: {
    label?: string | null;
    heading?: string | null;
    buttonLabel?: string | null;
    buttonUrl?: string | null;
    backgroundImage?: (number | null) | Media;
    externalBackgroundImageUrl?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsroom-page".
 */
export interface NewsroomPage {
  id: number;
  metaTitle?: string | null;
  hero: {
    title: string;
    descriptions: {
      body: string;
      id?: string | null;
    }[];
  };
  filters: {
    label: string;
    value: 'all' | 'insights' | 'news';
    id?: string | null;
  }[];
  posts?: (number | NewsPost)[] | null;
  finalCta?: {
    label?: string | null;
    heading?: string | null;
    buttonLabel?: string | null;
    buttonUrl?: string | null;
    backgroundImage?: (number | null) | Media;
    externalBackgroundImageUrl?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers-page".
 */
export interface CareersPage {
  id: number;
  metaTitle?: string | null;
  hero: {
    title: string;
    descriptions: {
      body: string;
      id?: string | null;
    }[];
  };
  teamPhotos: {
    image?: (number | null) | Media;
    externalImageUrl: string;
    imageAlt?: string | null;
    id?: string | null;
  }[];
  benefitsIntro: {
    bodyHtml: string;
    image?: (number | null) | Media;
    externalImageUrl: string;
    imageAlt?: string | null;
  };
  benefits: {
    number: string;
    title: string;
    body: string;
    id?: string | null;
  }[];
  clock: {
    locationLabel: string;
    timeZone: string;
    backgroundImage?: (number | null) | Media;
    externalBackgroundImageUrl: string;
  };
  positionsHeading: string;
  positions?: (number | JobPost)[] | null;
  finalCta?: {
    label?: string | null;
    heading?: string | null;
    buttonLabel?: string | null;
    buttonUrl?: string | null;
    backgroundImage?: (number | null) | Media;
    externalBackgroundImageUrl?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  metaTitle?: string | null;
  hero: {
    email?: string | null;
    title: string;
    backgroundImage?: (number | null) | Media;
    /**
     * Keep the current image here until the final DJI Luggage imagery is ready.
     */
    externalBackgroundImageUrl?: string | null;
  };
  form: {
    label?: string | null;
    title?: string | null;
    fields: {
      placeholder: string;
      id?: string | null;
    }[];
    messagePlaceholder?: string | null;
    submitLabel?: string | null;
    successMessage?: string | null;
    errorMessage?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandName?: T;
  logoLabel?: T;
  logoDisplay?: T;
  logoAlt?: T;
  logoHref?: T;
  logoImage?: T;
  externalLogoImageUrl?: T;
  darkLogoImage?: T;
  externalDarkLogoImageUrl?: T;
  requestQuoteLabel?: T;
  requestQuoteUrl?: T;
  mainNavigation?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  menuContact?:
    | T
    | {
        quickContactLabel?: T;
        email?: T;
        messageLabel?: T;
        quoteLabel?: T;
        quoteUrl?: T;
      };
  footerContact?:
    | T
    | {
        label?: T;
        heading?: T;
        buttonLabel?: T;
        buttonUrl?: T;
      };
  address?: T;
  footerColumns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  socialLinks?:
    | T
    | {
        label?: T;
        url?: T;
        icon?: T;
        id?: T;
      };
  copyright?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  metaTitle?: T;
  hero?:
    | T
    | {
        breadcrumb?: T;
        title?: T;
        description?: T;
        buttonLabel?: T;
        buttonUrl?: T;
        videoUrl?: T;
        posterUrl?: T;
      };
  services?:
    | T
    | {
        label?: T;
        heading?: T;
        cards?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        buttonLabel?: T;
        buttonUrl?: T;
      };
  values?:
    | T
    | {
        number?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  technologyCta?:
    | T
    | {
        label?: T;
        headingHtml?: T;
        buttonLabel?: T;
        buttonUrl?: T;
      };
  howWeWork?:
    | T
    | {
        label?: T;
        body?: T;
        steps?:
          | T
          | {
              number?: T;
              body?: T;
              id?: T;
            };
      };
  newsroom?:
    | T
    | {
        label?: T;
        heading?: T;
        posts?: T;
      };
  finalCta?:
    | T
    | {
        label?: T;
        heading?: T;
        buttonLabel?: T;
        buttonUrl?: T;
        backgroundImage?: T;
        externalBackgroundImageUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  metaTitle?: T;
  pageTitle?: T;
  heroImage?: T;
  externalHeroImageUrl?: T;
  whoWeAre?:
    | T
    | {
        label?: T;
        heading?: T;
        columns?:
          | T
          | {
              body?: T;
              id?: T;
            };
      };
  reach?:
    | T
    | {
        label?: T;
        heading?: T;
        locations?:
          | T
          | {
              country?: T;
              city?: T;
              id?: T;
            };
        globeVideoUrl?: T;
      };
  metrics?:
    | T
    | {
        label?: T;
        heading?: T;
        image?: T;
        externalImageUrl?: T;
        imageAlt?: T;
        subtext?: T;
        items?:
          | T
          | {
              value?: T;
              label?: T;
              tone?: T;
              id?: T;
            };
      };
  testimonials?: T;
  trustedLabel?: T;
  trustedLogos?: T;
  teamLabel?: T;
  teamHeading?: T;
  teamMembers?: T;
  careersCta?:
    | T
    | {
        label?: T;
        heading?: T;
        buttonLabel?: T;
        buttonUrl?: T;
      };
  finalCta?:
    | T
    | {
        label?: T;
        heading?: T;
        buttonLabel?: T;
        buttonUrl?: T;
        backgroundImage?: T;
        externalBackgroundImageUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page_select".
 */
export interface ServicesPageSelect<T extends boolean = true> {
  metaTitle?: T;
  hero?:
    | T
    | {
        label?: T;
        title?: T;
        description?: T;
        backgroundImage?: T;
        externalBackgroundImageUrl?: T;
        imageAlt?: T;
      };
  focus?:
    | T
    | {
        label?: T;
        heading?: T;
        paragraphs?:
          | T
          | {
              body?: T;
              id?: T;
            };
      };
  aerial?:
    | T
    | {
        image?: T;
        externalImageUrl?: T;
        imageAlt?: T;
        labels?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  services?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              number?: T;
              title?: T;
              description?: T;
              image?: T;
              externalImageUrl?: T;
              imageAlt?: T;
              id?: T;
            };
      };
  industries?:
    | T
    | {
        title?: T;
        image?: T;
        externalImageUrl?: T;
        imageAlt?: T;
        items?:
          | T
          | {
              name?: T;
              id?: T;
            };
      };
  finalCta?:
    | T
    | {
        label?: T;
        heading?: T;
        buttonLabel?: T;
        buttonUrl?: T;
        backgroundImage?: T;
        externalBackgroundImageUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-page_select".
 */
export interface PlatformPageSelect<T extends boolean = true> {
  metaTitle?: T;
  hero?:
    | T
    | {
        label?: T;
        title?: T;
        description?: T;
        backgroundImage?: T;
        externalBackgroundImageUrl?: T;
      };
  interfaceIntro?:
    | T
    | {
        label?: T;
        body?: T;
      };
  tabletMockup?:
    | T
    | {
        image?: T;
        externalImageUrl?: T;
        imageAlt?: T;
      };
  featureSections?:
    | T
    | {
        label?: T;
        heading?: T;
        body?: T;
        image?: T;
        externalImageUrl?: T;
        imageAlt?: T;
        id?: T;
      };
  whyChoose?:
    | T
    | {
        label?: T;
        body?: T;
        backgroundImage?: T;
        externalBackgroundImageUrl?: T;
      };
  highlights?:
    | T
    | {
        label?: T;
        heading?: T;
        items?:
          | T
          | {
              number?: T;
              body?: T;
              icon?: T;
              externalIconUrl?: T;
              iconAlt?: T;
              id?: T;
            };
      };
  finalCta?:
    | T
    | {
        label?: T;
        heading?: T;
        buttonLabel?: T;
        buttonUrl?: T;
        backgroundImage?: T;
        externalBackgroundImageUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsroom-page_select".
 */
export interface NewsroomPageSelect<T extends boolean = true> {
  metaTitle?: T;
  hero?:
    | T
    | {
        title?: T;
        descriptions?:
          | T
          | {
              body?: T;
              id?: T;
            };
      };
  filters?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  posts?: T;
  finalCta?:
    | T
    | {
        label?: T;
        heading?: T;
        buttonLabel?: T;
        buttonUrl?: T;
        backgroundImage?: T;
        externalBackgroundImageUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers-page_select".
 */
export interface CareersPageSelect<T extends boolean = true> {
  metaTitle?: T;
  hero?:
    | T
    | {
        title?: T;
        descriptions?:
          | T
          | {
              body?: T;
              id?: T;
            };
      };
  teamPhotos?:
    | T
    | {
        image?: T;
        externalImageUrl?: T;
        imageAlt?: T;
        id?: T;
      };
  benefitsIntro?:
    | T
    | {
        bodyHtml?: T;
        image?: T;
        externalImageUrl?: T;
        imageAlt?: T;
      };
  benefits?:
    | T
    | {
        number?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  clock?:
    | T
    | {
        locationLabel?: T;
        timeZone?: T;
        backgroundImage?: T;
        externalBackgroundImageUrl?: T;
      };
  positionsHeading?: T;
  positions?: T;
  finalCta?:
    | T
    | {
        label?: T;
        heading?: T;
        buttonLabel?: T;
        buttonUrl?: T;
        backgroundImage?: T;
        externalBackgroundImageUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  metaTitle?: T;
  hero?:
    | T
    | {
        email?: T;
        title?: T;
        backgroundImage?: T;
        externalBackgroundImageUrl?: T;
      };
  form?:
    | T
    | {
        label?: T;
        title?: T;
        fields?:
          | T
          | {
              placeholder?: T;
              id?: T;
            };
        messagePlaceholder?: T;
        submitLabel?: T;
        successMessage?: T;
        errorMessage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}